  vars:
   - temp_file: "pythonbrew-{{ pythonbrew_version }}"
   - temp_tarball: "{{ temp_file }}.tar.gz"
   - path_dists: "{{ home }}/dists"
   - path_downloads: '{{ path_dists }}/{{ temp_tarball }}'
   - path_temps: '{{ path_dists }}/{{ temp_file }}'


  tasks:
  - name: create dir to install
    command: mkdir -p {{ path_dists }}

  - name: remove old instalations downloads
    command: rm -rf {{ path_downloads }}

  - name: remove old instalations temp files
    command: rm -rf {{ path_temps }}

  - name: download
    get_url: url=http://pypi.python.org/packages/source/p/pythonbrew/{{ temp_tarball  }} dest={{ path_dists }}/{{ temp_tarball }}

  - name: extraction
    command: cd {{ path_dists }} ; tar zxf {{ temp_tarball }}

  - name: install pythonbrew
    command: PYTHONBREW_ROOT="{{ pythonbrew_location }}" python {{ path_dists }}/{{ temp_file }}/pythonbrew_install.py --systemwide
