
  - name: download and install
    shell: $"{{ pythonbrew_exe }}" install {{ python_version }}

  - name: use python
    shell: $"{{ pythonbrew_exe }}" use {{ python_version }}

  - name: install requirements.txt
    shell: $"{{ pip }}" -r {{ repo_dir }}/requeriments.txt