user: '{{ ansible_ssh_user }}'
home: '/home/{{ user }}'
venv: '{{ home }}/venv'
python: '{{ venv }}/bin/python'
profile: '{{ home }}/.zshrc'

site_dir: '{{ home }}/{{ site_url }}'
repo_dir: '{{ site_dir }}/{{ project_name }}'
public_dir: '{{ site_dir }}/public'

media_url: '/static/media/'
media_dir: '{{ public_dir }}{{ media_url }}'
static_url: '/static/collect/'
static_dir: '{{ public_dir }}{{ static_url }}'

oh_my_zsh: '{{ home }}/.oh-my-zsh'
zsh_theme: 'juanghurtado'

backup_media_path: '{{ home }}/media_{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.zip'
backup_media_path_link: '{{ home }}/media.zip'