
 - name: create settings_local
   template: src=settings_local.py.j2 dest={{ repo_dir }}/{{ project_name }}/settings_local.py

 - name: collect static
   django_manage: command=collectstatic virtualenv={{ venv }} app_path={{ repo_dir }}

 - name: migrate database
   django_manage: command=migrate virtualenv={{ venv }} app_path={{ repo_dir }}

 #- name: kill python to restart site todo:ainda n funciona
 #  shell: pkill {{ python }}