
 - name: create settings_local
   template: src=settings_local.py.j2 dest={{ repo_dir }}/{{ project_name }}/settings_local.py

 - name: collect static
   shell: $'{{ python }}' {{ repo_dir }}/manage.py collectstatic

 - name: migrate database
   shell: $'{{ python }}' {{ repo_dir }}/manage.py migrate